=== jorisrietveld/FinalXML2/Eindopdracht.dtd
<!ELEMENT Garages (Garage+)>

        <!--Hier worden de entiteiten van de garage aangemaakt -->
        <!ENTITY % dagen "(Maandag, Dinsdag, Woensdag, Donderdag, Vrijdag, Zaterdag, Zondag)">
        <!ENTITY % valuta "(euro|dollar)">

        <!-- Dit valideerd de gegevens die voor een garage opgeslagen kunnen worden. -->
        <!ELEMENT Garage (Naam, Adres, Telefoonnummer , Email, Fotos,Omschrijving?,Website?,
                Routebeschrijving?,AangeslotenOrganizaties?,VkOpeningstijden,WPOpeningstijden,
                Services? ,Automerken?,Faciliteiten?,Autos?,Werkzaamheden?,Medewerkers)>
        <!ELEMENT Naam (#PCDATA)>
        <!ELEMENT Adres (Straat, Huisnummer , Postcode , Plaats , Provincie)>
        <!ELEMENT Telefoonnummer (#PCDATA)>
        <!ELEMENT Email                (#PCDATA)>
        <!ELEMENT Fotos (Foto*)>
        <!ELEMENT Foto                 (#PCDATA)>
        <!ELEMENT Omschrijving         (#PCDATA)>
        <!ELEMENT Website              (#PCDATA)>
        <!ELEMENT Routebeschrijving    (#PCDATA)>
        <!ELEMENT AangeslotenOrganizaties (Organizatie+)>
        <!ELEMENT Organizatie (#PCDATA)>
        <!ATTLIST Organizatie naam CDATA #REQUIRED>

        <!-- Dit valideert de adressen-->
        <!ELEMENT Straat (#PCDATA)>
        <!ELEMENT Huisnummer (#PCDATA)>
        <!ELEMENT Postcode (#PCDATA)>
        <!ELEMENT Plaats (#PCDATA)>
        <!ELEMENT Provincie (#PCDATA)>

        <!-- Dit valideerd de openings tijden van de werkplaats en verkoop -->
        <!ELEMENT WPOpeningstijden %dagen;>
        <!ATTLIST WPOpeningstijden format CDATA #REQUIRED>
        <!ELEMENT VkOpeningstijden %dagen;>
        <!ATTLIST VkOpeningstijden format CDATA #REQUIRED>
        <!ELEMENT Maandag   (#PCDATA)>
        <!ELEMENT Dinsdag   (#PCDATA)>
        <!ELEMENT Woensdag  (#PCDATA)>
        <!ELEMENT Donderdag (#PCDATA)>
        <!ELEMENT Vrijdag   (#PCDATA)>
        <!ELEMENT Zaterdag  (#PCDATA)>
        <!ELEMENT Zondag    (#PCDATA)>

        <!-- Dit valideert de de beschibaare auto merken. -->
        <!ELEMENT Automerken (Automerk+)>
        <!ELEMENT Automerk  (#PCDATA)>

        <!-- Dit valideert de medewerkers. -->
        <!ELEMENT   Medewerkers (Medewerker+)>
        <!ELEMENT   Medewerker  (Naam, Foto , Functie)>
        <!ELEMENT   Functie     (#PCDATA)>

        <!-- Dit valideerd de werkzaamheden. -->
        <!ELEMENT   Werkzaamheden   (Werkzaamheid+)>
        <!ELEMENT   Werkzaamheid (#PCDATA)>

        <!-- Dit valideerd de Services -->
        <!ELEMENT   Services (Service+)>
        <!ELEMENT   Service (#PCDATA)>

        <!-- Dit valideerd de gegevens van auto's  -->
        <!ELEMENT Autos (Auto+)>
        <!ELEMENT Auto (Kenteken, Automerk, Type, Bouwjaar, Brandstof, Prijs, DatumAPK, Fotos)>
        <!ELEMENT Kenteken (#PCDATA)>
        <!ELEMENT Type (#PCDATA)>
        <!ELEMENT Bouwjaar (#PCDATA)>
        <!ATTLIST Bouwjaar format CDATA #REQUIRED>
        <!ELEMENT Brandstoffen (Benzine?, Gas?, Diesel?)?>
        <!ELEMENT Brandstof (Benzine|Gas|Diesel)>

        <!ELEMENT Benzine (#PCDATA)>
        <!ELEMENT Gas (#PCDATA)>
        <!ELEMENT Diesel (#PCDATA)>

        <!ELEMENT Prijs         (#PCDATA)>
        <!ATTLIST Prijs valuta %valuta; #REQUIRED>

        <!-- Dit vaideerd the datam tot waar de APK gedig is. -->
        <!ELEMENT DatumAPK      (Jaar, Maand, Dag)>
        <!ELEMENT Jaar (#PCDATA)>
        <!ELEMENT Maand (#PCDATA)>
        <!ELEMENT Dag (#PCDATA)>

        <!-- Dit valideerd de beschibare facilieiten. -->
        <!ELEMENT Faciliteiten  (Pompen?,Wasbox?,Wasstraat?,Winkel?)>
        <!ELEMENT Pompen (Pomp*)>
        <!ELEMENT Pomp (Brandstoffen)>
        <!ELEMENT Wasbox    EMPTY>
        <!ELEMENT Wasstraat EMPTY>

        <!-- Dit valideerd de gegevens van een winkel. -->
        <!ELEMENT Winkel (Producten*)>
        <!ELEMENT Producten (Product+)>
        <!ELEMENT Product (#PCDATA)>

=== jorisrietveld/FinalXML2/Eindopdracht.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Garages SYSTEM "eindopdracht.dtd">
<Garages>
    <Garage>
        <!-- Dit zijn de gegevens van de garage -->
        <Naam>Angelslo's auto's</Naam>
        <Adres>
            <Straat>Hoofdstraat</Straat>
            <Huisnummer>25</Huisnummer>
            <Postcode>7821 AS</Postcode>
            <Plaats>Emmen</Plaats>
            <Provincie>Drenthe</Provincie>
        </Adres>
        <Telefoonnummer>06-12345678</Telefoonnummer>
        <Email>autos-angelslo@hotmail.com</Email>
        <Fotos>
            <Foto>logo.jpg</Foto>
        </Fotos>
        <Omschrijving>Wij verkopen nieuwe en tweedehands auto's</Omschrijving>
        <Website>www.angelslo-autos.nl</Website>
        <Routebeschrijving>https://goo.gl/maps/vJ9j4VVUofS2</Routebeschrijving>

        <!-- Dit zijn de organizaties waarbij de garage is aangesloten -->
        <AangeslotenOrganizaties>
            <Organizatie naam="BOVAG"/>
            <Organizatie naam="RDW"/>
        </AangeslotenOrganizaties>

        <!-- De openingstijden van de verkoop -->
        <VkOpeningstijden format="HH:MM - HH:MM">
            <Maandag>08:00 - 17:00</Maandag>
            <Dinsdag>08:00 - 17:00</Dinsdag>
            <Woensdag>08:00 - 17:00</Woensdag>
            <Donderdag>08:00 - 20:00</Donderdag>
            <Vrijdag>08:00 - 17:00</Vrijdag>
            <Zaterdag>08:00 - 17:00</Zaterdag>
            <Zondag>12:00 - 17:00</Zondag>
        </VkOpeningstijden>

        <!-- De openings tijden van de werkplaats -->
        <WPOpeningstijden format="HH:MM - HH:MM">
            <Maandag>08:00 - 18:00</Maandag>
            <Dinsdag>08:00 - 18:00</Dinsdag>
            <Woensdag>08:00 - 18:00</Woensdag>
            <Donderdag>08:00 - 21:00</Donderdag>
            <Vrijdag>08:00 - 18:00</Vrijdag>
            <Zaterdag>08:00 - 17:00</Zaterdag>
            <Zondag>12:00 - 17:00</Zondag>
        </WPOpeningstijden>

        <!-- Dit zijn de sercies die de garage aanbied -->
        <Services>
            <Service>Huren</Service>
            <Service>lenen</Service>
        </Services>

        <!-- Dit zijn de de merken waarvan de garage een officiele dealer is-->
        <Automerken>
            <Automerk>Ford</Automerk>
            <Automerk>Kia</Automerk>
            <Automerk>Mercedes</Automerk>
        </Automerken>

        <!-- Dit zijn de facaliteiten die de garage aanbied -->
        <Faciliteiten>
            <Pompen>
                <Pomp>
                    <Brandstoffen>
                        <Benzine />
                        <Gas />
                        <Diesel />
                    </Brandstoffen>
                </Pomp>
            </Pompen>
            <Wasbox/>
        </Faciliteiten>

        <!-- Dit zijn de auto's die de garage verkoopt -->
        <Autos>
            <Auto>
                <Kenteken>98-RR-XX</Kenteken>
                <Automerk>Mazda</Automerk>
                <Type>Cabrio</Type>
                <Bouwjaar format="yyyy">2005</Bouwjaar>
                <Brandstof>
                    <Benzine />
                </Brandstof>
                <Prijs valuta="euro">10000</Prijs>
                <!-- Dit is de datum waarop de APK afloopt. -->
                <DatumAPK>
                    <Jaar>2019</Jaar>
                    <Maand>01</Maand>
                    <Dag>20</Dag>
                </DatumAPK>

                <Fotos>
                    <Foto>Front.jpg</Foto>
                    <Foto>Back.jpg</Foto>
                    <Foto>Inside.jpg</Foto>
                    <Foto>Motor.jpg</Foto>
                </Fotos>
            </Auto>
        </Autos>

        <!-- Dit zijn de werkzaam heden die de garage aanbied -->
        <Werkzaamheden>
            <Werkzaamheid>onderhoud</Werkzaamheid>
            <Werkzaamheid>APKKeuring</Werkzaamheid>
            <Werkzaamheid>BandenService</Werkzaamheid>
        </Werkzaamheden>

        <!-- Dit zijn de medewerkers die werkzaam zijn bij de garage. -->
        <Medewerkers>
            <Medewerker>
                <Naam>Jos Harmsen</Naam>
                <Foto>jos.jpg</Foto>
                <Functie>Pompbediende</Functie>
            </Medewerker>
            <Medewerker>
                <Naam>Gerard Provrex</Naam>
                <Foto>me.jpg</Foto>
                <Functie>Monteur</Functie>
            </Medewerker>
        </Medewerkers>
    </Garage>
</Garages>
